# -*- coding: utf-8 -*-
"""my_app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6Ao8r86nYYh_U0BMf3YFKp6HeS0Bx56
"""


import streamlit as st
import pandas as pd
import numpy as np

st.write("My First Streamlit Web App")
chart_data = pd.DataFrame(np.random.randn(20, 3), columns=['a', 'b', 'c'])
st.write(chart_data)

